name: Node.js CI

on:
  push:
  pull_request: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependencies in server directory
      - name: Install dependencies
        run: npm install
        working-directory: ./server

      # Build can be included if there is a build script in your package.json
      - name: Build
        run: npm run build --if-present
        working-directory: ./server

      # Run tests in server directory
      - name: Run tests
        run: npm test
        working-directory: ./server
