name: Node.js CI

on:
  push:
  pull_request: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    # Set up your environment variables here using the secrets
    - name: Set Environment Variables
      run: |
        echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_ENV
        echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> $GITHUB_ENV

    # Install dependencies in server directory
    - name: Install dependencies
      run: npm install
      working-directory: ./server

    # Build can be included if there is a build script in your package.json
    - name: Build
      run: npm run build --if-present
      working-directory: ./server

    # Run tests in server directory
    - name: Run tests
      run: |
        export SUPABASE_URL=${{ secrets.SUPABASE_URL }}
        export SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
        export SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        export PLAID_CLIENT_ID=${{ secrets.PLAID_CLIENT_ID }}

        export PLAID_SECRET=${{ secrets.PLAID_SECRET }}
        export PLAID_ENV=${{ secrets.PLAID_ENV }}


        npm test
      working-directory: ./server
